http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  auth:
    host: localhost
    paths:
      - '/v1/auth/login'
  users:
    host: localhost
    paths: 
      - '/v1/users'
      - '/v1/users/*'
      - '/v1/user/register'
      - '/v1/user/verification/*'
      - '/v1/user/block_user/*'
  cars:
    host: localhost
    paths:
      - '/v1/cars'
  brands:
    host: localhost
    paths:
      - '/v1/brands'
serviceEndpoints:
  authService:
    url: 'http://localhost:3001'
  usersService:
    url: 'http://localhost:3002'
  carsService:
    url: 'http://localhost:3003'
  brandsService:
    url: 'http://localhost:3004'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: auth-service
    apiEndpoints:
      - auth
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: authService
             changeOrigin: true
  - name: users-service
    apiEndpoints:
      - users
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: usersService
             changeOrigin: true
  - name: cars-service
    apiEndpoints:
      - cars
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: carsService
             changeOrigin: true
  - name: brands-service
    apiEndpoints:
      - brands
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: brandsService
             changeOrigin: true
