http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  auth:
    host: localhost
    paths:
      - '/v1/auth/login'
  users:
    host: localhost
    paths: 
      - '/v1/users'
      - '/v1/users/*'
      - '/v1/user/register'
serviceEndpoints:
  authService:
    url: 'http://localhost:3001'
  usersService:
    url: 'http://localhost:3002'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: auth-service
    apiEndpoints:
      - auth
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: authService
             changeOrigin: true
  - name: users-service
    apiEndpoints:
      - users
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: usersService
             changeOrigin: true
