http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  auth:
    host: localhost
    paths:
      - '/v1/auth/login'
  users:
    host: localhost
    paths:
      - '/v1/users'
      - '/v1/users/*'
      - '/v1/register'
      - '/v1/verification/*'
      - '/v1/block_user/*'
  cars:
    host: localhost
    paths:
      - '/v1/cars'
      - '/v1/cars/*'
      - '/v1/add_new_car'
      - '/v1/update_car/*'
      - '/v1/delete_car/*'
  brands:
    host: localhost
    paths:
      - '/v1/brands'
      - '/v1/brands/*'
      - '/v1/add_new_brand'
      - '/v1/update_brand/*'
      - '/v1/delete_brand/*'
  events:
    host: localhost
    paths:
      - '/v1/events'
      - '/v1/events/*'
      - '/v1/add_new_event'
serviceEndpoints:
  authService:
    url: 'http://localhost:3001'
  usersService:
    url: 'http://localhost:3002'
  carsService:
    url: 'http://localhost:3003'
  brandsService:
    url: 'http://localhost:3004'
  eventsService:
    url: 'http://localhost:3005'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: auth-service
    apiEndpoints:
      - auth
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: authService
             changeOrigin: true
  - name: users-service
    apiEndpoints:
      - users
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: usersService
             changeOrigin: true
  - name: cars-service
    apiEndpoints:
      - cars
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: carsService
             changeOrigin: true
  - name: brands-service
    apiEndpoints:
      - brands
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: brandsService
             changeOrigin: true
  - name: events-service
    apiEndpoints:
      - events
    policies:
      - cors:
        - action:
             origin: '*'
      - proxy:
        - action:
             serviceEndpoint: eventsService
             changeOrigin: true
